#!/usr/bin/env python3
"""
Slack Formatter Utility
Formats crew digest output for Slack posting
"""

import json
from datetime import datetime
from typing import Dict, Any

def format_for_slack(
    scout_output: str,
    analyst_output: str,
    homelab_output: str,
    work_output: str,
    metadata: Dict[str, Any]
) -> str:
    """
    Format digest sections into Slack-friendly markdown (Criterion 4 format)

    Args:
        scout_output: Scout agent output (tagged signals)
        analyst_output: Analyst synthesis
        homelab_output: Homelab Strategist opportunities
        work_output: Work Strategist opportunities
        metadata: Dict with sources_count, signals_count, timestamp

    Returns:
        Formatted Slack message (markdown)
    """

    # Build message
    lines = []

    # Header
    lines.append("📊 *Strategic Intelligence Digest*")
    lines.append(f"_{metadata.get('timestamp', datetime.now().strftime('%Y-%m-%d %H:%M'))}_")
    lines.append(f"Sources monitored: {metadata.get('sources_count', 'N/A')} | Signals analyzed: {metadata.get('signals_count', 'N/A')}")
    lines.append("")

    # Scout Section (condensed)
    lines.append("---")
    lines.append("*🔍 SCOUT SIGNALS*")
    lines.append("")
    # Take first 500 chars of scout output as summary
    scout_preview = scout_output[:500] + "..." if len(scout_output) > 500 else scout_output
    lines.append(scout_preview)
    lines.append("")

    # Analyst Section
    lines.append("---")
    lines.append("*🧠 ANALYST SYNTHESIS*")
    lines.append("")
    # Take first 800 chars of analyst output
    analyst_preview = analyst_output[:800] + "..." if len(analyst_output) > 800 else analyst_output
    lines.append(analyst_preview)
    lines.append("")

    # Homelab Opportunities
    lines.append("---")
    lines.append("*🏠 HOMELAB OPPORTUNITIES*")
    lines.append("")
    lines.append(homelab_output)
    lines.append("")

    # Work Opportunities
    lines.append("---")
    lines.append("*💼 WORK OPPORTUNITIES*")
    lines.append("")
    lines.append(work_output)
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("_Generated by CrewAI Strategic Intelligence_")

    return "\n".join(lines)

def format_for_slack_with_opportunities(
    scout_output: str,
    analyst_output: str,
    homelab_opportunities: Dict[str, Dict[str, str]],
    work_opportunities: Dict[str, Dict[str, str]],
    metadata: Dict[str, Any]
) -> str:
    """
    Format digest with numbered opportunities (Criterion 5 format)

    Args:
        scout_output: Scout agent output
        analyst_output: Analyst synthesis
        homelab_opportunities: Dict of H* opportunities (from opportunity_parser)
        work_opportunities: Dict of W* opportunities (from opportunity_parser)
        metadata: Sources count, signals count, timestamp

    Returns:
        Formatted Slack message with numbered opportunities
    """
    try:
        from tools.opportunity_parser import format_opportunity_for_slack
    except ImportError:
        # For local testing
        from opportunity_parser import format_opportunity_for_slack

    lines = []

    # Header
    lines.append("📊 *Strategic Intelligence Digest*")
    lines.append(f"_{metadata.get('timestamp', '')}_")
    lines.append(f"Sources: {metadata.get('sources_count', 'N/A')} | Signals: {metadata.get('signals_count', 'N/A')}")
    lines.append("")

    # Scout Section (condensed preview)
    lines.append("---")
    lines.append("*🔍 SCOUT SIGNALS*")
    lines.append("")
    scout_preview = scout_output[:500] + "..." if len(scout_output) > 500 else scout_output
    lines.append(scout_preview)
    lines.append("")

    # Analyst Section (condensed preview)
    lines.append("---")
    lines.append("*🧠 ANALYST SYNTHESIS*")
    lines.append("")
    analyst_preview = analyst_output[:800] + "..." if len(analyst_output) > 800 else analyst_output
    lines.append(analyst_preview)
    lines.append("")

    # Homelab Opportunities (numbered)
    lines.append("---")
    lines.append("*🏠 HOMELAB OPPORTUNITIES*")
    lines.append("")
    if homelab_opportunities:
        for opp_id in sorted(homelab_opportunities.keys()):
            opp_text = format_opportunity_for_slack(opp_id, homelab_opportunities[opp_id])
            lines.append(opp_text)
    else:
        lines.append("_No homelab opportunities identified today_")
    lines.append("")

    # Work Opportunities (numbered)
    lines.append("---")
    lines.append("*💼 WORK OPPORTUNITIES*")
    lines.append("")
    if work_opportunities:
        for opp_id in sorted(work_opportunities.keys()):
            opp_text = format_opportunity_for_slack(opp_id, work_opportunities[opp_id])
            lines.append(opp_text)
    else:
        lines.append("_No work opportunities identified today_")
    lines.append("")

    # Footer with approval syntax instructions
    lines.append("---")
    lines.append("_Reply: `approve [ID] [type]` to generate deliverable_")
    lines.append("_Types: `plan` (homelab), `brief` or `slide` (work)_")
    lines.append("_Example: `approve H1, W1 brief`_")

    return "\n".join(lines)

def create_slack_payload(formatted_message: str, channel: str = "#trend-monitoring") -> Dict[str, Any]:
    """
    Create full Slack API payload

    Args:
        formatted_message: Pre-formatted message text
        channel: Slack channel name (default: #trend-monitoring)

    Returns:
        Dict ready for Slack API POST
    """
    return {
        "channel": channel,
        "text": formatted_message,
        "unfurl_links": False,
        "unfurl_media": False
    }

def save_for_n8n(
    scout_output: str,
    analyst_output: str,
    homelab_output: str,
    work_output: str,
    metadata: Dict[str, Any],
    output_file: str = "output/slack_digest.json"
) -> str:
    """
    Save formatted output to JSON file for n8n to consume (Criterion 4 format)

    Args:
        scout_output: Scout agent output
        analyst_output: Analyst synthesis
        homelab_output: Homelab Strategist opportunities
        work_output: Work Strategist opportunities
        metadata: Digest metadata
        output_file: Path to save JSON

    Returns:
        Path to saved file
    """

    # Format for Slack
    slack_message = format_for_slack(
        scout_output, analyst_output, homelab_output, work_output, metadata
    )

    # Create payload
    payload = {
        "timestamp": metadata.get('timestamp', datetime.now().isoformat()),
        "sources_count": metadata.get('sources_count', 0),
        "signals_count": metadata.get('signals_count', 0),
        "slack_message": slack_message,
        "raw_outputs": {
            "scout": scout_output,
            "analyst": analyst_output,
            "homelab": homelab_output,
            "work": work_output
        }
    }

    # Save to file
    with open(output_file, 'w') as f:
        json.dump(payload, f, indent=2)

    return output_file

def save_for_n8n_with_opportunities(
    scout_output: str,
    analyst_output: str,
    homelab_opportunities: Dict[str, Dict[str, str]],
    work_opportunities: Dict[str, Dict[str, str]],
    metadata: Dict[str, Any],
    output_file: str = None
) -> str:
    """
    Save formatted output with numbered opportunities (Criterion 5 format)

    Args:
        scout_output: Scout agent output
        analyst_output: Analyst synthesis
        homelab_opportunities: Dict of H* opportunities
        work_opportunities: Dict of W* opportunities
        metadata: Digest metadata
        output_file: Path to save JSON (auto-generated if None)

    Returns:
        Path to saved file
    """
    if output_file is None:
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        output_file = f"output/slack_digest_{timestamp}.json"

    # Format for Slack with numbered opportunities
    slack_message = format_for_slack_with_opportunities(
        scout_output, analyst_output,
        homelab_opportunities, work_opportunities,
        metadata
    )

    # Create payload
    payload = {
        "timestamp": metadata.get('timestamp', datetime.now().isoformat()),
        "sources_count": metadata.get('sources_count', 0),
        "signals_count": metadata.get('signals_count', 0),
        "slack_message": slack_message,
        "opportunities": {
            "homelab": homelab_opportunities,
            "work": work_opportunities
        },
        "raw_outputs": {
            "scout": scout_output,
            "analyst": analyst_output
        }
    }

    # Save to file
    with open(output_file, 'w') as f:
        json.dump(payload, f, indent=2)

    return output_file

# Quick test function
if __name__ == "__main__":
    test_metadata = {
        "timestamp": "2026-02-02 03:30:00",
        "sources_count": 5,
        "signals_count": 3
    }

    # Test Criterion 4 format
    print("Testing Criterion 4 format...")
    test_message = format_for_slack(
        "Test scout output",
        "Test analyst output",
        "Test homelab opportunities",
        "Test work opportunities",
        test_metadata
    )
    print(test_message)

    # Test Criterion 5 format
    print("\n" + "="*60)
    print("Testing Criterion 5 format with numbered opportunities...")
    print("="*60 + "\n")

    test_homelab_opps = {
        "H1": {
            "title": "Local LLM Fine-tuning",
            "relevance": "Connects to AI Box project",
            "signal": "New quantization techniques announced",
            "next_steps": "Research Ollama fine-tuning"
        }
    }

    test_work_opps = {
        "W1": {
            "title": "AI Code Review Patterns",
            "relevance": "Velocity improvement goals",
            "signal": "Claude Code review capabilities emerging",
            "next_steps": "Pilot with one sprint"
        }
    }

    test_message_numbered = format_for_slack_with_opportunities(
        "Test scout output",
        "Test analyst output",
        test_homelab_opps,
        test_work_opps,
        test_metadata
    )
    print(test_message_numbered)
